[
    [
        "mainmenu",
        "427",
        "widget",
        "DiscWidget"
    ],
    [
        "mainmenu",
        "427",
        "widgetName",
        "427"
    ],
    [
        "mainmenu",
        "427",
        "background",
        "special://skin/extras/home-images/disc.jpg"
    ],
    [
        "mainmenu",
        "427",
        "icon",
        "icons/sidemenu/disc.png"
    ],
    [
        "mainmenu",
        "movies",
        "widget",
        "MoviesWidget"
    ],
    [
        "mainmenu",
        "movies",
        "widgetName",
        "342"
    ],
    [
        "mainmenu",
        "movies",
        "background",
        "special://skin/extras/home-images/movies.jpg"
    ],
    [
        "mainmenu",
        "movies",
        "icon",
        "icons/sidemenu/movies.png"
    ],
    [
        "mainmenu",
        "movies",
        "icon",
        "icons/sidemenu/movies.png"
    ],
    [
        "mainmenu",
        "movies",
        "icon",
        "icons/sidemenu/movies.png"
    ],
    [
        "mainmenu",
        "movies--0",
        "widget",
        "MoviesWidget"
    ],
    [
        "mainmenu",
        "movies--0",
        "widgetName",
        "342"
    ],
    [
        "mainmenu",
        "movies--0",
        "background",
        "special://skin/extras/home-images/movies.jpg"
    ],
    [
        "mainmenu",
        "movies--0",
        "icon",
        "icons/sidemenu/movies.png"
    ],
    [
        "mainmenu",
        "movies--1",
        "widget",
        "PersonalWidgetList"
    ],
    [
        "mainmenu",
        "movies--1",
        "widgetName",
        "Movies List"
    ],
    [
        "mainmenu",
        "movies--1",
        "background",
        "special://skin/extras/home-images/movies.jpg"
    ],
    [
        "mainmenu",
        "movies--1",
        "widgetType",
        ""
    ],
    [
        "mainmenu",
        "movies--1",
        "widgetTarget",
        ""
    ],
    [
        "mainmenu",
        "movies--1",
        "widgetPath",
        "PersonalWidgetList"
    ],
    [
        "mainmenu",
        "movies--1",
        "icon",
        "icons/sidemenu/movies.png"
    ],
    [
        "mainmenu",
        "tvshows",
        "widget",
        "TVShowsWidget"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetName",
        "20343"
    ],
    [
        "mainmenu",
        "tvshows",
        "background",
        "special://skin/extras/home-images/tvshows.jpg"
    ],
    [
        "mainmenu",
        "tvshows",
        "icon",
        "icons/sidemenu/tv.png"
    ],
    [
        "mainmenu",
        "tvshows",
        "icon",
        "icons/sidemenu/tv.png"
    ],
    [
        "mainmenu",
        "tvshows",
        "icon",
        "icons/sidemenu/tv.png"
    ],
    [
        "mainmenu",
        "tvshows--0",
        "widget",
        "TVShowsWidget"
    ],
    [
        "mainmenu",
        "tvshows--0",
        "widgetName",
        "20343"
    ],
    [
        "mainmenu",
        "tvshows--0",
        "background",
        "special://skin/extras/home-images/tvshows.jpg"
    ],
    [
        "mainmenu",
        "tvshows--0",
        "icon",
        "icons/sidemenu/tv.png"
    ],
    [
        "mainmenu",
        "tvshows--1",
        "widget",
        "PersonalWidgetList"
    ],
    [
        "mainmenu",
        "tvshows--1",
        "widgetName",
        "TV Shows Lists"
    ],
    [
        "mainmenu",
        "tvshows--1",
        "background",
        "special://skin/extras/home-images/tvshows.jpg"
    ],
    [
        "mainmenu",
        "tvshows--1",
        "widgetType",
        ""
    ],
    [
        "mainmenu",
        "tvshows--1",
        "widgetTarget",
        ""
    ],
    [
        "mainmenu",
        "tvshows--1",
        "widgetPath",
        "PersonalWidgetList"
    ],
    [
        "mainmenu",
        "tvshows--1",
        "icon",
        "icons/sidemenu/tv.png"
    ],
    [
        "mainmenu",
        "19020",
        "widget",
        "LiveTVWidget"
    ],
    [
        "mainmenu",
        "19020",
        "widgetName",
        "19020"
    ],
    [
        "mainmenu",
        "19020",
        "background",
        "special://skin/extras/home-images/livetv.jpg"
    ],
    [
        "mainmenu",
        "19020",
        "icon",
        "icons/sidemenu/livetv.png"
    ],
    [
        "mainmenu",
        "24001",
        "widget",
        "AddonsWidget"
    ],
    [
        "mainmenu",
        "24001",
        "widgetName",
        "24001"
    ],
    [
        "mainmenu",
        "24001",
        "background",
        "special://skin/extras/home-images/addons.jpg"
    ],
    [
        "mainmenu",
        "24001",
        "icon",
        "icons/sidemenu/addons.png"
    ],
    [
        "mainmenu",
        "favorites",
        "widget",
        "FavoritesWidget"
    ],
    [
        "mainmenu",
        "favorites",
        "widgetName",
        "10134"
    ],
    [
        "mainmenu",
        "favorites",
        "background",
        "special://skin/extras/home-images/favorites.jpg"
    ],
    [
        "mainmenu",
        "favorites",
        "icon",
        "icons/sidemenu/favourites.png"
    ],
    [
        "mainmenu",
        "8",
        "widget",
        "WeatherWidget"
    ],
    [
        "mainmenu",
        "8",
        "widgetName",
        "8"
    ],
    [
        "mainmenu",
        "8",
        "background",
        "special://skin/extras/home-images/weather.jpg"
    ],
    [
        "mainmenu",
        "8",
        "icon",
        "icons/sidemenu/weather.png"
    ],
    [
        "mainmenu",
        "8",
        "icon",
        "icons/sidemenu/weather.png"
    ],
    [
        "mainmenu",
        "8--0",
        "widget",
        "WeatherWidget"
    ],
    [
        "mainmenu",
        "8--0",
        "widgetName",
        "8"
    ],
    [
        "mainmenu",
        "8--0",
        "background",
        "special://skin/extras/home-images/weather.jpg"
    ],
    [
        "mainmenu",
        "8--0",
        "icon",
        "icons/sidemenu/weather.png"
    ],
    [
        "mainmenu",
        "libreelec",
        "background",
        "special://skin/extras/home-images/libreelec.png"
    ],
    [
        "mainmenu",
        "libreelec",
        "icon",
        "icons/sidemenu/libreelec.png"
    ],
    [
        "mainmenu",
        "coreelec",
        "background",
        "special://skin/extras/home-images/coreelec.png"
    ],
    [
        "mainmenu",
        "coreelec",
        "icon",
        "icons/sidemenu/coreelec.png"
    ]
]